name: audly
description: An audiobook player inspired by ios books and audio book player for android.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable:
  build_runner:

flutter:
  uses-material-design: true
